//
// Created by hugues on 12/12/24.
//

#ifndef THINSHELLS_CONSTANTS_H
#define THINSHELLS_CONSTANTS_H

double BENDING_STIFFNESS = 10.0;
double STRETCHING_STIFFNESS = 1.0;
double DAMPING = 0.1;

#endif //THINSHELLS_CONSTANTS_H
