//
// Created by hugues on 12/12/24.
//

#ifndef THINSHELLS_CONSTANTS_H
#define THINSHELLS_CONSTANTS_H

#define BENDING_STIFFNESS  10.0
#define STRETCHING_STIFFNESS 1.0
#define DAMPING = 0.1

#define N_FACES_MESH 100

#define TOLERANCE_NEWTON 1e-4
#define MAX_ITERATIONS_NEWTON 30

#define SIMULATION_DT 0.4
#define SIMULATION_NEWMARK_BETA 0.25
#define SIMULATION_NEWMARK_GAMMA 0.5

#endif //THINSHELLS_CONSTANTS_H
